INSERT INTO countries (name, iso_a2, iso_a3, capital, metadata) VALUES
('Afghanistan', 'AF', 'AFG', 'Kabul', 'this is metadata'),
('Albania', 'AL', 'ALB', 'Tirana', 'this is metadata'),
('Algeria', 'DZ', 'DZA', 'Algiers', 'this is metadata'),
('Andorra', 'AD', 'AND', 'Andorra la Vella', 'this is metadata'),
('Angola', 'AO', 'AGO', 'Luanda', 'this is metadata'),
('Antigua and Barbuda', 'AG', 'ATG', 'Saint John''s', 'this is metadata'),
('Argentina', 'AR', 'ARG', 'Buenos Aires', 'this is metadata'),
('Armenia', 'AM', 'ARM', 'Yerevan', 'this is metadata'),
('Australia', 'AU', 'AUS', 'Canberra', 'this is metadata'),
('Austria', 'AT', 'AUT', 'Vienna', 'this is metadata'),
('Azerbaijan', 'AZ', 'AZE', 'Baku', 'this is metadata'),
('Bahamas', 'BS', 'BHS', 'Nassau', 'this is metadata'),
('Bahrain', 'BH', 'BHR', 'Manama', 'this is metadata'),
('Bangladesh', 'BD', 'BGD', 'Dhaka', 'this is metadata'),
('Barbados', 'BB', 'BRB', 'Bridgetown', 'this is metadata'),
('Belarus', 'BY', 'BLR', 'Minsk', 'this is metadata'),
('Belgium', 'BE', 'BEL', 'Brussels', 'this is metadata'),
('Belize', 'BZ', 'BLZ', 'Belmopan', 'this is metadata'),
('Benin', 'BJ', 'BEN', 'Porto-Novo', 'this is metadata'),
('Bhutan', 'BT', 'BTN', 'Thimphu', 'this is metadata'),
('Bolivia', 'BO', 'BOL', 'Sucre', 'this is metadata'),
('Bosnia and Herzegovina', 'BA', 'BIH', 'Sarajevo', 'this is metadata'),
('Botswana', 'BW', 'BWA', 'Gaborone', 'this is metadata'),
('Brazil', 'BR', 'BRA', 'Brasília', 'this is metadata'),
('Brunei', 'BN', 'BRN', 'Bandar Seri Begawan', 'this is metadata'),
('Bulgaria', 'BG', 'BGR', 'Sofia', 'this is metadata'),
('Burkina Faso', 'BF', 'BFA', 'Ouagadougou', 'this is metadata'),
('Burundi', 'BI', 'BDI', 'Gitega', 'this is metadata'),
('Cabo Verde', 'CV', 'CPV', 'Praia', 'this is metadata'),
('Cambodia', 'KH', 'KHM', 'Phnom Penh', 'this is metadata'),
('Cameroon', 'CM', 'CMR', 'Yaoundé', 'this is metadata'),
('Canada', 'CA', 'CAN', 'Ottawa', 'this is metadata'),
('Central African Republic', 'CF', 'CAF', 'Bangui', 'this is metadata'),
('Chad', 'TD', 'TCD', 'N''Djamena', 'this is metadata'),
('Chile', 'CL', 'CHL', 'Santiago', 'this is metadata'),
('China', 'CN', 'CHN', 'Beijing', 'this is metadata'),
('Colombia', 'CO', 'COL', 'Bogotá', 'this is metadata'),
('Comoros', 'KM', 'COM', 'Moroni', 'this is metadata'),
('Congo', 'CG', 'COG', 'Brazzaville', 'this is metadata'),
('Democratic Republic of the Congo', 'CD', 'COD', 'Kinshasa', 'this is metadata'),
('Costa Rica', 'CR', 'CRI', 'San José', 'this is metadata'),
('Croatia', 'HR', 'HRV', 'Zagreb', 'this is metadata'),
('Cuba', 'CU', 'CUB', 'Havana', 'this is metadata'),
('Cyprus', 'CY', 'CYP', 'Nicosia', 'this is metadata'),
('Czech Republic', 'CZ', 'CZE', 'Prague', 'this is metadata'),
('Denmark', 'DK', 'DNK', 'Copenhagen', 'this is metadata'),
('Djibouti', 'DJ', 'DJI', 'Djibouti', 'this is metadata'),
('Dominica', 'DM', 'DMA', 'Roseau', 'this is metadata'),
('Dominican Republic', 'DO', 'DOM', 'Santo Domingo', 'this is metadata'),
('Ecuador', 'EC', 'ECU', 'Quito', 'this is metadata'),
('Egypt', 'EG', 'EGY', 'Cairo', 'this is metadata'),
('El Salvador', 'SV', 'SLV', 'San Salvador', 'this is metadata'),
('Equatorial Guinea', 'GQ', 'GNQ', 'Malabo', 'this is metadata'),
('Eritrea', 'ER', 'ERI', 'Asmara', 'this is metadata'),
('Estonia', 'EE', 'EST', 'Tallinn', 'this is metadata'),
('Eswatini', 'SZ', 'SWZ', 'Mbabane', 'this is metadata'),
('Ethiopia', 'ET', 'ETH', 'Addis Ababa', 'this is metadata'),
('Fiji', 'FJ', 'FJI', 'Suva', 'this is metadata'),
('Finland', 'FI', 'FIN', 'Helsinki', 'this is metadata'),
('France', 'FR', 'FRA', 'Paris', 'this is metadata'),
('Gabon', 'GA', 'GAB', 'Libreville', 'this is metadata'),
('Gambia', 'GM', 'GMB', 'Banjul', 'this is metadata'),
('Georgia', 'GE', 'GEO', 'Tbilisi', 'this is metadata'),
('Germany', 'DE', 'DEU', 'Berlin', 'this is metadata'),
('Ghana', 'GH', 'GHA', 'Accra', 'this is metadata'),
('Greece', 'GR', 'GRC', 'Athens', 'this is metadata'),
('Grenada', 'GD', 'GRD', 'Saint George''s', 'this is metadata'),
('Guatemala', 'GT', 'GTM', 'Guatemala City', 'this is metadata'),
('Guinea', 'GN', 'GIN', 'Conakry', 'this is metadata'),
('Guinea-Bissau', 'GW', 'GNB', 'Bissau', 'this is metadata'),
('Guyana', 'GY', 'GUY', 'Georgetown', 'this is metadata'),
('Haiti', 'HT', 'HTI', 'Port-au-Prince', 'this is metadata'),
('Honduras', 'HN', 'HND', 'Tegucigalpa', 'this is metadata'),
('Hungary', 'HU', 'HUN', 'Budapest', 'this is metadata'),
('Iceland', 'IS', 'ISL', 'Reykjavik', 'this is metadata'),
('India', 'IN', 'IND', 'New Delhi', 'this is metadata'),
('Indonesia', 'ID', 'IDN', 'Jakarta', 'this is metadata'),
('Iran', 'IR', 'IRN', 'Tehran', 'this is metadata'),
('Iraq', 'IQ', 'IRQ', 'Baghdad', 'this is metadata'),
('Ireland', 'IE', 'IRL', 'Dublin', 'this is metadata'),
('Israel', 'IL', 'ISR', 'Jerusalem', 'this is metadata'),
('Italy', 'IT', 'ITA', 'Rome', 'this is metadata'),
('Ivory Coast', 'CI', 'CIV', 'Yamoussoukro', 'this is metadata'),
('Jamaica', 'JM', 'JAM', 'Kingston', 'this is metadata'),
('Japan', 'JP', 'JPN', 'Tokyo', 'this is metadata'),
('Jordan', 'JO', 'JOR', 'Amman', 'this is metadata'),
('Kazakhstan', 'KZ', 'KAZ', 'Astana', 'this is metadata'),
('Kenya', 'KE', 'KEN', 'Nairobi', 'this is metadata'),
('Kiribati', 'KI', 'KIR', 'Tarawa', 'this is metadata'),
('Kosovo', 'XK', 'XKX', 'Pristina', 'this is metadata'),
('Kuwait', 'KW', 'KWT', 'Kuwait City', 'this is metadata'),
('Kyrgyzstan', 'KG', 'KGZ', 'Bishkek', 'this is metadata'),
('Laos', 'LA', 'LAO', 'Vientiane', 'this is metadata'),
('Latvia', 'LV', 'LVA', 'Riga', 'this is metadata'),
('Lebanon', 'LB', 'LBN', 'Beirut', 'this is metadata'),
('Lesotho', 'LS', 'LSO', 'Maseru', 'this is metadata'),
('Liberia', 'LR', 'LBR', 'Monrovia', 'this is metadata'),
('Libya', 'LY', 'LBY', 'Tripoli', 'this is metadata'),
('Liechtenstein', 'LI', 'LIE', 'Vaduz', 'this is metadata'),
('Lithuania', 'LT', 'LTU', 'Vilnius', 'this is metadata'),
('Luxembourg', 'LU', 'LUX', 'Luxembourg', 'this is metadata'),
('Madagascar', 'MG', 'MDG', 'Antananarivo', 'this is metadata'),
('Malawi', 'MW', 'MWI', 'Lilongwe', 'this is metadata'),
('Malaysia', 'MY', 'MYS', 'Kuala Lumpur', 'this is metadata'),
('Maldives', 'MV', 'MDV', 'Malé', 'this is metadata'),
('Mali', 'ML', 'MLI', 'Bamako', 'this is metadata'),
('Malta', 'MT', 'MLT', 'Valletta', 'this is metadata'),
('Marshall Islands', 'MH', 'MHL', 'Majuro', 'this is metadata'),
('Mauritania', 'MR', 'MRT', 'Nouakchott', 'this is metadata'),
('Mauritius', 'MU', 'MUS', 'Port Louis', 'this is metadata'),
('Mexico', 'MX', 'MEX', 'Mexico City', 'this is metadata'),
('Micronesia', 'FM', 'FSM', 'Palikir', 'this is metadata'),
('Moldova', 'MD', 'MDA', 'Chișinău', 'this is metadata'),
('Monaco', 'MC', 'MCO', 'Monaco', 'this is metadata'),
('Mongolia', 'MN', 'MNG', 'Ulaanbaatar', 'this is metadata'),
('Montenegro', 'ME', 'MNE', 'Podgorica', 'this is metadata'),
('Morocco', 'MA', 'MAR', 'Rabat', 'this is metadata'),
('Mozambique', 'MZ', 'MOZ', 'Maputo', 'this is metadata'),
('Myanmar', 'MM', 'MMR', 'Naypyidaw', 'this is metadata'),
('Namibia', 'NA', 'NAM', 'Windhoek', 'this is metadata'),
('Nauru', 'NR', 'NRU', 'Yaren', 'this is metadata'),
('Nepal', 'NP', 'NPL', 'Kathmandu', 'this is metadata'),
('Netherlands', 'NL', 'NLD', 'Amsterdam', 'this is metadata'),
('New Zealand', 'NZ', 'NZL', 'Wellington', 'this is metadata'),
('Nicaragua', 'NI', 'NIC', 'Managua', 'this is metadata'),
('Niger', 'NE', 'NER', 'Niamey', 'this is metadata'),
('Nigeria', 'NG', 'NGA', 'Abuja', 'this is metadata'),
('North Korea', 'KP', 'PRK', 'Pyongyang', 'this is metadata'),
('North Macedonia', 'MK', 'MKD', 'Skopje', 'this is metadata'),
('Norway', 'NO', 'NOR', 'Oslo', 'this is metadata'),
('Oman', 'OM', 'OMN', 'Muscat', 'this is metadata'),
('Pakistan', 'PK', 'PAK', 'Islamabad', 'this is metadata'),
('Palau', 'PW', 'PLW', 'Ngerulmud', 'this is metadata'),
('Palestine', 'PS', 'PSE', 'Ramallah', 'this is metadata'),
('Panama', 'PA', 'PAN', 'Panama City', 'this is metadata'),
('Papua New Guinea', 'PG', 'PNG', 'Port Moresby', 'this is metadata'),
('Paraguay', 'PY', 'PRY', 'Asunción', 'this is metadata'),
('Peru', 'PE', 'PER', 'Lima', 'this is metadata'),
('Philippines', 'PH', 'PHL', 'Manila', 'this is metadata'),
('Poland', 'PL', 'POL', 'Warsaw', 'this is metadata'),
('Portugal', 'PT', 'PRT', 'Lisbon', 'this is metadata'),
('Qatar', 'QA', 'QAT', 'Doha', 'this is metadata'),
('Romania', 'RO', 'ROU', 'Bucharest', 'this is metadata'),
('Russia', 'RU', 'RUS', 'Moscow', 'this is metadata'),
('Rwanda', 'RW', 'RWA', 'Kigali', 'this is metadata'),
('Saint Kitts and Nevis', 'KN', 'KNA', 'Basseterre', 'this is metadata'),
('Saint Lucia', 'LC', 'LCA', 'Castries', 'this is metadata'),
('Saint Vincent and the Grenadines', 'VC', 'VCT', 'Kingstown', 'this is metadata'),
('Samoa', 'WS', 'WSM', 'Apia', 'this is metadata'),
('San Marino', 'SM', 'SMR', 'San Marino', 'this is metadata'),
('Sao Tome and Principe', 'ST', 'STP', 'São Tomé', 'this is metadata'),
('Saudi Arabia', 'SA', 'SAU', 'Riyadh', 'this is metadata'),
('Senegal', 'SN', 'SEN', 'Dakar', 'this is metadata'),
('Serbia', 'RS', 'SRB', 'Belgrade', 'this is metadata'),
('Seychelles', 'SC', 'SYC', 'Victoria', 'this is metadata'),
('Sierra Leone', 'SL', 'SLE', 'Freetown', 'this is metadata'),
('Singapore', 'SG', 'SGP', 'Singapore', 'this is metadata'),
('Slovakia', 'SK', 'SVK', 'Bratislava', 'this is metadata'),
('Slovenia', 'SI', 'SVN', 'Ljubljana', 'this is metadata'),
('Solomon Islands', 'SB', 'SLB', 'Honiara', 'this is metadata'),
('Somalia', 'SO', 'SOM', 'Mogadishu', 'this is metadata'),
('South Africa', 'ZA', 'ZAF', 'Pretoria', 'this is metadata'),
('South Korea', 'KR', 'KOR', 'Seoul', 'this is metadata'),
('South Sudan', 'SS', 'SSD', 'Juba', 'this is metadata'),
('Spain', 'ES', 'ESP', 'Madrid', 'this is metadata'),
('Sri Lanka', 'LK', 'LKA', 'Sri Jayawardenepura Kotte', 'this is metadata'),
('Sudan', 'SD', 'SDN', 'Khartoum', 'this is metadata'),
('Suriname', 'SR', 'SUR', 'Paramaribo', 'this is metadata'),
('Sweden', 'SE', 'SWE', 'Stockholm', 'this is metadata'),
('Switzerland', 'CH', 'CHE', 'Bern', 'this is metadata'),
('Syria', 'SY', 'SYR', 'Damascus', 'this is metadata'),
('Taiwan', 'TW', 'TWN', 'Taipei', 'this is metadata'),
('Tajikistan', 'TJ', 'TJK', 'Dushanbe', 'this is metadata'),
('Tanzania', 'TZ', 'TZA', 'Dodoma', 'this is metadata'),
('Thailand', 'TH', 'THA', 'Bangkok', 'this is metadata'),
('Timor-Leste', 'TL', 'TLS', 'Dili', 'this is metadata'),
('Togo', 'TG', 'TGO', 'Lomé', 'this is metadata'),
('Tonga', 'TO', 'TON', 'Nukuʻalofa', 'this is metadata'),
('Trinidad and Tobago', 'TT', 'TTO', 'Port of Spain', 'this is metadata'),
('Tunisia', 'TN', 'TUN', 'Tunis', 'this is metadata'),
('Turkey', 'TR', 'TUR', 'Ankara', 'this is metadata'),
('Turkmenistan', 'TM', 'TKM', 'Ashgabat', 'this is metadata'),
('Tuvalu', 'TV', 'TUV', 'Funafuti', 'this is metadata'),
('Uganda', 'UG', 'UGA', 'Kampala', 'this is metadata'),
('Ukraine', 'UA', 'UKR', 'Kyiv', 'this is metadata'),
('United Arab Emirates', 'AE', 'ARE', 'Abu Dhabi', 'this is metadata'),
('United Kingdom', 'GB', 'GBR', 'London', 'this is metadata'),
('United States of America', 'US', 'USA', 'Washington, D.C.', 'this is metadata'),
('Uruguay', 'UY', 'URY', 'Montevideo', 'this is metadata'),
('Uzbekistan', 'UZ', 'UZB', 'Tashkent', 'this is metadata'),
('Vanuatu', 'VU', 'VUT', 'Port Vila', 'this is metadata'),
('Vatican City', 'VA', 'VAT', 'Vatican City', 'this is metadata'),
('Venezuela', 'VE', 'VEN', 'Caracas', 'this is metadata'),
('Vietnam', 'VN', 'VNM', 'Hanoi', 'this is metadata'),
('Yemen', 'YE', 'YEM', 'Sana''a', 'this is metadata'),
('Zambia', 'ZM', 'ZMB', 'Lusaka', 'this is metadata'),
('Zimbabwe', 'ZW', 'ZWE', 'Harare', 'this is metadata'),
('French Southern Territories', 'TF', 'ATF', 'Saint-Pierre', 'this is metadata'),
('Greenland', 'GL', 'GRL', 'Nuuk', 'this is metadata'),
('Puerto Rico', 'PR', 'PRI', 'San Juan', 'this is metadata'),
('Western Sahara', 'EH', 'ESH', 'Laayoune', 'this is metadata'),
('Antarctica', 'AQ', 'ATA', 'N/A', 'this is metadata'),
('Falkland Islands', 'FK', 'FLK', 'Stanley', 'this is metadata'),
('New Caledonia', 'NC', 'NCL', 'Nouméa', 'this is metadata'),
('French Guiana', 'GF', 'GUF', 'Cayenne', 'this is metadata'),
('Somaliland', 'XS', 'SOL', 'Hargeisa', 'this is metadata'),
('Northern Cyprus', 'XN', 'XNC', 'North Nicosia', 'this is metadata')
ON CONFLICT (iso_a3) DO NOTHING;
